In [3]:
import pandas as pd
import numpy as np

In [22]:
file_name = ['daily_sales_data_0.csv', 'daily_sales_data_1.csv', 'daily_sales_data_2.csv']
data_frames = [pd.read_csv('data/' + file) for file in file_name]
data_combined = pd.concat(data_frames, ignore_index=True)
print(f"Combined data shape: {data_combined.shape}")
data_combined.head()

Combined data shape: (41160, 5)

       product  price  quantity        date region
0  pink morsel  $3.00       546  2018-02-06  north
1  pink morsel  $3.00       549  2018-02-06  south
2  pink morsel  $3.00       577  2018-02-06   east
3  pink morsel  $3.00       519  2018-02-06   west
4  gold morsel  $9.99       580  2018-02-06  north

In [16]:
data_filtered_by_product  = data_combined[data_combined['product'].str.lower() =='pink morsel']
data_filtered_by_product['price'] = data_filtered_by_product['price'].str.replace('$', '', regex=False).str.replace(',', '').astype(float)
print(f"Filtered data shape: {data_filtered_by_product.shape}")
data_filtered_by_product.head()

Filtered data shape: (1960, 5)

C:\Users\amine\AppData\Local\Temp\ipykernel_25248\4266245497.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered_by_product['price'] = data_filtered_by_product['price'].str.replace('$', '', regex=False).str.replace(',', '').astype(float)

        product  price  quantity        date region
0   pink morsel    3.0       546  2018-02-06  north
1   pink morsel    3.0       549  2018-02-06  south
2   pink morsel    3.0       577  2018-02-06   east
3   pink morsel    3.0       519  2018-02-06   west
28  pink morsel    3.0       529  2018-02-07  north

In [18]:
print(f'{data_filtered_by_product.info()}')
data_filtered_by_product['sales'] = data_filtered_by_product['price'] * data_filtered_by_product['quantity']
data_filtered_by_product.head()

<class 'pandas.core.frame.DataFrame'>
Index: 1960 entries, 0 to 13695
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   product   1960 non-null   object
 1   price     1960 non-null   float64
 2   quantity  1960 non-null   int64
 3   date      1960 non-null   object
 4   region    1960 non-null   object
 5   sales     1960 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 107.2+ KB
None

C:\Users\amine\AppData\Local\Temp\ipykernel_25248\3456432067.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered_by_product['sales'] = data_filtered_by_product['price'] * data_filtered_by_product['quantity']

        product  price  quantity        date region   sales
0   pink morsel    3.0       546  2018-02-06  north  1638.0
1   pink morsel    3.0       549  2018-02-06  south  1647.0
2   pink morsel    3.0       577  2018-02-06   east  1731.0
3   pink morsel    3.0       519  2018-02-06   west  1557.0
28  pink morsel    3.0       529  2018-02-07  north  1587.0

In [19]:
data_filtered_by_product.to_csv('data/pink_morsel_sales.csv', index=False)

In [23]:
import pandas as pd
import numpy as np

# Define the file names
files_name = ['daily_sales_data_0.csv', 'daily_sales_data_1.csv', 'daily_sales_data_2.csv']

# Read and combine all CSV files
data_frames = [pd.read_csv('data/' + file) for file in files_name]
data_combined = pd.concat(data_frames, ignore_index=True)

print(f"Combined data shape: {data_combined.shape}")
print("\nFirst few rows of combined data:")
print(data_combined.head())

# Filter for Pink Morsel only
data_filtered_by_product = data_combined[data_combined['product'].str.lower() == 'pink morsel']

# Clean the price field (remove $ and commas, convert to float)
data_filtered_by_product['price'] = data_filtered_by_product['price'].str.replace('$', '', regex=False).str.replace(',', '').astype(float)

print(f"\nFiltered data shape: {data_filtered_by_product.shape}")
print("\nFirst few rows of filtered data:")
print(data_filtered_by_product.head())

print(f"\nData info:")
print(data_filtered_by_product.info())

# Calculate sales (price * quantity)
data_filtered_by_product['sales'] = data_filtered_by_product['price'] * data_filtered_by_product['quantity']

print("\nFirst few rows with sales calculated:")
print(data_filtered_by_product.head())

# Select only the required fields: sales, date, region
output_data = data_filtered_by_product[['sales', 'date', 'region']]

print("\nFinal output data:")
print(output_data.head())

# Save to output file
output_data.to_csv('data/pink_morsel_sales.csv', index=False)

print(f"\nOutput saved to data/pink_morsel_sales.csv")
print(f"Output shape: {output_data.shape}")

Combined data shape: (41160, 5)

First few rows of combined data:
       product  price  quantity        date region
0  pink morsel  $3.00       546  2018-02-06  north
1  pink morsel  $3.00       549  2018-02-06  south
2  pink morsel  $3.00       577  2018-02-06   east
3  pink morsel  $3.00       519  2018-02-06   west
4  gold morsel  $9.99       580  2018-02-06  north

Filtered data shape: (5880, 5)

First few rows of filtered data:
        product  price  quantity        date region
0   pink morsel    3.0       546  2018-02-06  north
1   pink morsel    3.0       549  2018-02-06  south
2   pink morsel    3.0       577  2018-02-06   east
3   pink morsel    3.0       519  2018-02-06   west
28  pink morsel    3.0       529  2018-02-07  north

Data info:
<class 'pandas.core.frame.DataFrame'>
Index: 5880 entries, 0 to 41135
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   product   5880 non-null   object
 1   price     5880 non-null   float64
 2   quantity  5880 non-null   int64
 3   date      5880 non-null   object
 4   region    5880 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 275.6+ KB
None

First few rows with sales calculated:
        product  price  quantity        date region   sales
0   pink morsel    3.0       546  2018-02-06  north  1638.0
1   pink morsel    3.0       549  2018-02-06  south  1647.0
2   pink morsel    3.0       577  2018-02-06   east  1731.0
3   pink morsel    3.0       519  2018-02-06   west  1557.0
28  pink morsel    3.0       529  2018-02-07  north  1587.0

Final output data:
     sales        date region
0   1638.0  2018-02-06  north
1   1647.0  2018-02-06  south
2   1731.0  2018-02-06   east
3   1557.0  2018-02-06   west
28  1587.0  2018-02-07  north

Output saved to data/pink_morsel_sales.csv
Output shape: (5880, 3)

C:\Users\amine\AppData\Local\Temp\ipykernel_25248\2931629374.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered_by_product['price'] = data_filtered_by_product['price'].str.replace('$', '', regex=False).str.replace(',', '').astype(float)
C:\Users\amine\AppData\Local\Temp\ipykernel_25248\2931629374.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered_by_product['sales'] = data_filtered_by_product['price'] * data_filtered_by_product['quantity']